### ISSUE TITLE
Breaks normal usage of setTitleColor

### ISSUE THREAD

**Issue by 3lvis** [NSElvis/UIButton-ANDYHighlighted#3]
- Install the category via CocoaPods
- Open a ViewController
- Add a button
- Set the outlet
- Change color in `viewDidLoad` 

``` objc
[self.superAwesomeButton setTitleColor:[UIColor greenColor] forState:UIControlStateHighlighted];
```

Sample project:
https://github.com/uzegonemad/hyperoslo-form-uibutton-issues

**Comment by uzegonemad** [comment]
Hey @3lvis, this is primarily in response to https://github.com/hyperoslo/Form/issues/415.

While this workaround would most likely work, I've got a good 20-30 buttons that break when this category is in use. Most of the buttons have images which darken on highlight, so the preferred fix would be something that doesn't require modifying core functionality.

**Comment by 3lvis** [comment]
@uzegonemad Definitely! I agree, it should just work.

**Comment by LightMan** [comment]
Hi Elvis, me again.

I am facing this issue, I changed your code, so the first time the button is clicked it takes automatically the normal and highlighted title color from the button. So there is no need to establish by code the title color. And buttons in xibs/storyboards  with a custom highlight text colors will work ok with this.

Have a look and tell me what you think.

``` objc
- (void)setHighlighted:(BOOL)highlighted
{
    [super setHighlighted:highlighted];

    if (self.highlightedTitleColor == nil){
        self.highlightedTitleColor = [self titleColorForState:UIControlStateHighlighted];
    }

    if (self.titleColor == nil){
        self.titleColor = [self titleColorForState:UIControlStateNormal];
    }

    if (self.highlightedTitleColor && self.titleColor) {
        UIColor *titleColor = self.highlighted ? self.highlightedTitleColor : self.titleColor;
        [self setTitleColor:titleColor forState:UIControlStateNormal];
        [self setTitleColor:titleColor forState:UIControlStateHighlighted];
        [self setTitleColor:titleColor forState:UIControlStateSelected];
    }

    if (self.highlightedBackgroundColor && self.originalColor) {
        self.backgroundColor = self.highlighted ? self.highlightedBackgroundColor : self.originalColor;
    }
}

```

**Comment by 3lvis** [comment]
@LightMan Wow, David. You came to save the day. This definitely fixes the issue. I'll push an update.

Thanks a lot!

**Comment by skarctop** [comment]
all button will be gray after click, but i don't want that, this is still not well

**Comment by skarctop** [comment]
it affect all buttons - not just those implemented in Form. why do you use category

**Comment by 3lvis** [comment]
@skarctop It's a category, and should only affect your buttons if you use any of the added attributes.

<img width="572" alt="screen shot 2016-09-14 at 07 40 07" src="https://cloud.githubusercontent.com/assets/1088217/18501139/9032a76c-7a4e-11e6-86b1-e308fbcf3760.png">

**Comment by LightMan** [comment]
Well, I had to change  `- (void)setHighlighted:(BOOL)highlighted` method because it was affecting all buttons in my app. By default when buttons are pressed they change to the highlighted colour, so I tried to "patch" this method to adopt the default behaviour if the buttons were not using the FORM library. But I guess if you don't want the default behaviour for buttons, grey colour when pressed, this will not work.

IMHO FORM should not use categories that override the default behaviour or any SDK's methods. Anyway, since I used this library I will gladly help to whatever changes are needed, but I think this will imply a decent change. @3lvis what do you think?

**Comment by 3lvis** [comment]
@LightMan Makes sense :) Go for it.
