### ISSUE TITLE
Conflict with another library - LEAmountInputView

### ISSUE THREAD

**Issue by jeffleeismyhero** [NSElvis/UIButton-ANDYHighlighted#5]
This repo displays the issue I'm experiencing with button highlighting.

https://github.com/jeffleeismyhero/UIButton-ANDYHighlighted-LEAmountInputView

When a button is clicked, it is never un-highlighted. Any ideas?

**Comment by 3lvis** [comment]
Oh god. 😱

**Comment by 3lvis** [comment]
I think the best would be to just remove this dependency.

**Comment by jeffleeismyhero** [comment]
This branch doesn't have the issue, but there is no highlighting at all:

https://github.com/jeffleeismyhero/UIButton-ANDYHighlighted-LEAmountInputView/tree/with-v0.2.1

**Comment by 3lvis** [comment]
@jeffleeismyhero can you try with Form in master? This dependency should be removed now.

**Comment by jeffleeismyhero** [comment]
Thanks, that fixed it!

**Comment by 3lvis** [comment]
I also updated this library to stop using the Objective-C runtime.

https://github.com/3lvis/UIButton-ANDYHighlighted/releases/tag/2.0.0
